import { MenuItem, CategoryInfo } from './types';
import * as Banners from './images/categoryBanners';
import * as Items from './images/menuItems';

export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'BURGER',
    title: 'Burgers',
    urduTitle: 'برگر',
    description: 'Crispy Zingers & Juicy Flame-Smash Grilled Burgers',
    accentColor: '#FFD700',
    bannerImage: Banners.BURGER_BANNER,
  },
  {
    id: 'BROAST',
    title: 'Broast',
    urduTitle: 'بروسٹ',
    description: 'Super Crispy Fried Chicken cooked with classic Karachi recipe',
    accentColor: '#8B0000',
    bannerImage: Banners.BROAST_BANNER,
  },
  {
    id: 'FRIES',
    title: 'French Fries',
    urduTitle: 'فرائز',
    description: 'Hot & Seasoned Crispy Golden Potato Fries',
    accentColor: '#FFD700',
    bannerImage: Banners.FRIES_BANNER,
  },
  {
    id: 'SANDWICHES',
    title: 'Sandwiches',
    urduTitle: 'سینڈوچ',
    description: 'Grilled Triple-Decker Club Sandwiches served with Fries',
    accentColor: '#8B0000',
    bannerImage: Banners.SANDWICH_BANNER,
  },
  {
    id: 'BBQ',
    title: 'Charcoal BBQ',
    urduTitle: 'بار بی کیو',
    description: 'Fresh Off Red Coals: Tikka Boti, Malai Boti, and Seekh Kababs',
    accentColor: '#FFD700',
    bannerImage: Banners.BBQ_BANNER,
  },
  {
    id: 'DEALS',
    title: 'Mega Deals',
    urduTitle: 'ڈیلز',
    description: 'Specially discounted combo offers for maximum value & taste',
    accentColor: '#8B0000',
    bannerImage: Banners.DEALS_BANNER,
  },
  {
    id: 'ROLL',
    title: 'Paratha Rolls',
    urduTitle: 'رول پراٹھا',
    description: 'Spicy Seekh Kabab, Chicken Tikka & Zinger strips rolled in flaky paratha',
    accentColor: '#FFD700',
    bannerImage: Banners.ROLL_BANNER,
  },
  {
    id: 'BEVERAGES',
    title: 'Beverages',
    urduTitle: 'مشروبات',
    description: 'Chilled drinks to quench your thirst',
    accentColor: '#8B0000',
    bannerImage: Banners.BEVERAGES_BANNER,
  },
  {
    id: 'SIDES',
    title: 'Sides & Extras',
    urduTitle: 'اضافی اشیاء',
    description: 'Crispy Parathas, extra buns, and signature spicy dip sauces',
    accentColor: '#FFD700',
    bannerImage: Banners.SIDES_BANNER,
  },
];

export const MENU_ITEMS: MenuItem[] = [
  // --- BURGER ---
  {
    id: 'b1',
    name: 'Mighty Double Zinger Burger',
    urduName: 'مائٹی ڈبل زنگر',
    category: 'BURGER',
    description: 'Double crunchy breast fillet, double yellow melted cheese slice, crisp fresh iceberg lettuce, and double dollop of signature spicy house relish.',
    price: 490,
    imageUrl: Items.b1,
    isPopular: true,
    isSpicy: true,
    tags: ['Double Fillet', 'Cheese Loaded', 'Staff Choice'],
  },
  {
    id: 'b2',
    name: 'Spicy Chicken Zinger Burger',
    urduName: 'اسپائسی زنگر برگر',
    category: 'BURGER',
    description: 'Golden crunchy marinated chicken breast layer topped with cool fresh shredded cabbage, drizzled in our original secret garlic-mayo dressing inside a sesame bun.',
    price: 340,
    imageUrl: Items.b2,
    isPopular: true,
    isSpicy: true,
    tags: ['Best Seller', 'Extra Crispy'],
  },
  {
    id: 'b3',
    name: 'Beef Cheese Smash Burger',
    urduName: 'بیف چیز اسمیش برگر',
    category: 'BURGER',
    description: 'Premium beef mince patty hand-smashed on high temperature flat top griddle, loaded with melted cheddar cheese, grilled soft onions, and tangy dill pickles.',
    price: 390,
    imageUrl: Items.b3,
    isPopular: false,
    isSpicy: false,
    tags: ['100% Beef', 'Juicy Grill'],
  },
  {
    id: 'b4',
    name: 'Classic Chicken Patty Burger',
    urduName: 'چکن پیٹی برگر',
    category: 'BURGER',
    description: 'Traditional deep-fried chicken patty spiced with local pepper blends, dressed with real premium mayonnaise, and served with cucumber slices.',
    price: 250,
    imageUrl: Items.b4,
    isPopular: false,
    isSpicy: false,
    tags: ['Kids Choice', 'Mild Taste'],
  },

  // --- BROAST ---
  {
    id: 'br1',
    name: 'Crispy Quarter Chest Broast',
    urduName: 'کرسپی کوارٹر چیسٹ بروسٹ',
    category: 'BROAST',
    description: 'Crispy, premium-cut chicken breast piece injected with secret tandoori herbal brine, golden deep fried. Served with salted fries, toasted bun, and hot garlic sauce.',
    price: 410,
    imageUrl: Items.br1,
    isPopular: true,
    isSpicy: true,
    tags: ['Hot Seller', 'Karachi Special', 'With Bun & Sauce'],
  },
  {
    id: 'br2',
    name: 'Crispy Quarter Leg Broast',
    urduName: 'کرسپی کوارٹر لیگ بروسٹ',
    category: 'BROAST',
    description: 'Juiciest thigh/leg chicken quarter crunched with double flour coating, spice injected. Served with golden fries, bun, and our thick garlic paste.',
    price: 380,
    imageUrl: Items.br2,
    isPopular: false,
    isSpicy: true,
    tags: ['Extra Juicy', 'With Bun & Sauce'],
  },
  {
    id: 'br3',
    name: 'Kami Special Half Broast (2 Pcs)',
    urduName: 'کامی ہاف بروسٹ ڈبل',
    category: 'BROAST',
    description: 'Two gigantic pieces of golden-fried crispy broast chicken (one breast, one leg piece) served with double fries, 2 toasted buns, and 2 garlic dips.',
    price: 760,
    imageUrl: Items.br3,
    isPopular: true,
    isSpicy: true,
    tags: ['Hunger Buster', 'Saves Money'],
  },
  {
    id: 'br4',
    name: 'Mega Full Broast (4 Pcs)',
    urduName: 'فیملی فل بروسٹ',
    category: 'BROAST',
    description: 'Complete crispy chicken (4 full parts broast) coated in signature secret batter, served with 4 soft hamburger buns, family-sized fries plate, and 4 garlic mayo dips.',
    price: 1450,
    imageUrl: Items.br4,
    isPopular: false,
    isSpicy: true,
    tags: ['Family Pack', 'Big Savings'],
  },

  // --- FRIES ---
  {
    id: 'f1',
    name: 'Karachi Masala Fries',
    urduName: 'کراچی مصالحہ فرائز',
    category: 'FRIES',
    description: 'Fresh potato finger chips deep fried to amber perfection, tossed in a hot and fragrant local chatpata salt masala mix straight from Korangi market.',
    price: 190,
    imageUrl: Items.f1,
    isPopular: true,
    isSpicy: true,
    tags: ['Street Style', 'Spicy kick'],
  },
  {
    id: 'f2',
    name: 'Garlic Mayo Loaded Fries',
    urduName: 'گارلک مایو فرائز',
    category: 'FRIES',
    description: 'Large shareable plate of golden fries layered with signature creamy garlic sauce, spicy jalapeños, and sprinkled black seed pepper.',
    price: 270,
    imageUrl: Items.f2,
    isPopular: true,
    tags: ['Creamy Deep', 'Loaded Delicious'],
  },
  {
    id: 'f3',
    name: 'Cheesy Melt French Fries',
    urduName: 'چیز پگھلی فرائز',
    category: 'FRIES',
    description: 'Thick cut french fries drenched in rich liquid cheddar gold cheese sauce, baked briefly and topped with red chili flakes.',
    price: 340,
    imageUrl: Items.f3,
    tags: ['Warm Cheese', 'Pure Indulgence'],
  },

  // --- SANDWICHES ---
  {
    id: 's1',
    name: 'Kami Special Giant Club Sandwich',
    urduName: 'کامی اسپیشل کلب سینڈوچ',
    category: 'SANDWICHES',
    description: 'Four buttered bread slices toasted containing smoky chicken tikka bits, golden fried real egg, high cheddar cheese, cooling lettuce leaves, and thick tomatoes. Served with complimentary salted fries.',
    price: 340,
    imageUrl: Items.s1,
    isPopular: true,
    tags: ['Hearty Meal', 'With Fries', 'Mega Club'],
  },
  {
    id: 's2',
    name: 'Smoky BBQ Tikka Sandwich',
    urduName: 'اسموکی تکہ سینڈوچ',
    category: 'SANDWICHES',
    description: 'Charcoal grilled tikka boti bits mixed with local green chili raita and dhabba-style mint spread, sandwiched in 3 golden bread pieces.',
    price: 290,
    imageUrl: Items.s2,
    isSpicy: true,
    tags: ['Charcoal Taste', 'Spicy Chutney'],
  },

  // --- BBQ ---
  {
    id: 'bq1',
    name: 'Juicy Chicken Tikka Chest Piece',
    urduName: 'چکن تکہ چیسٹ (سینہ)',
    category: 'BBQ',
    description: 'A large Chicken chest section fully marinated in hot red vinegar, red chili flakes, crushed Pakistani spices, charcoal-grilled to absolute smokiness. Served with onions, lemon wedge, and mint dahi raita.',
    price: 260,
    imageUrl: Items.bq1,
    isPopular: true,
    isSpicy: true,
    tags: ['Charcoal Hot', '100% Spicy', 'Local Hero'],
  },
  {
    id: 'bq2',
    name: 'Mouth-Melting Malai Boti Plate (8 Pcs)',
    urduName: 'ملائی بوٹی پلیٹ (۸ دانے)',
    category: 'BBQ',
    description: '8 pieces of buttery boneless chicken chunks marinated in high fat milk cream, raw papaya, coriander, and mild white pepper, flame kissed. Served with signature mint green sauce.',
    price: 370,
    imageUrl: Items.bq2,
    isPopular: true,
    tags: ['Creamy BBQ', 'Soft Boneless'],
  },
  {
    id: 'bq3',
    name: 'Smoky Beef Seekh Kabab',
    urduName: 'سیخ کباب بیف',
    category: 'BBQ',
    description: '4 heavy skewer logs of beef fine-minced meat combined with local coriander, ginger pastes and crushed green chilies, smoked over coal fires.',
    price: 280,
    imageUrl: Items.bq3,
    isSpicy: true,
    tags: ['Beef Special', 'Hot Charcoal'],
  },

  // --- DEALS ---
  {
    id: 'd1',
    name: 'Deal 1: Single Zinger combo',
    urduName: 'ڈیل ۱: سنگل زنگر مکس',
    category: 'DEALS',
    description: '1 Spicy Chicken Zinger Burger, standard local Masala French Fries, and 1 icy cold 250ml Soft Drink can of your choice.',
    price: 430,
    imageUrl: Items.d1,
    isPopular: true,
    isSpicy: true,
    tags: ['Super Value', 'Most Ordered'],
  },
  {
    id: 'd2',
    name: 'Deal 2: BBQ Lovers Feast',
    urduName: 'ڈیل ۲: بار بی کیو ڈیل',
    category: 'DEALS',
    description: '1 Juicy Chicken Tikka Chest section, 2 piping hot crispy puri parathas, onion salad rings, raita chutney, and a chilled can drink.',
    price: 460,
    imageUrl: Items.d2,
    isPopular: true,
    isSpicy: true,
    tags: ['Night Delight', 'Tikka + Paratha combo'],
  },
  {
    id: 'd3',
    name: 'Deal 3: Broast Munch Combo',
    urduName: 'ڈیل ۳: بروسٹ منچ',
    category: 'DEALS',
    description: '1 crunchy Quarter Chicken Leg Broast piece, fresh bun, seasoned fries packet, garlic dip cup, and 1 cold Soft Drink.',
    price: 470,
    imageUrl: Items.d3,
    tags: ['Crusty Treat'],
  },
  {
    id: 'd4',
    name: 'Deal 4: Family Triple Dhamaka',
    urduName: 'ڈیل ۴: فیملی دھماکہ',
    category: 'DEALS',
    description: '2 Crispy Spicy Zinger Burgers, 1 Club Sandwich with Fries, 1 Quarter Broast chest piece, 2 garlic dips, and 1 chilled bottle of 1.5 Litre Jumbo Soft Drink.',
    price: 1390,
    imageUrl: Items.d4,
    isPopular: true,
    tags: ['Full House Feast', 'Mega Discount'],
  },

  // --- ROLL ---
  {
    id: 'r1',
    name: 'Chicken Chatpata Tikka Paratha Roll',
    urduName: 'چکن چٹپٹا رول',
    category: 'ROLL',
    description: 'Spicy charcoal tandoori chicken chunks layered with hot red imli chutney and white onion rings, wrapped securely in fresh flaky pan-fried paratha.',
    price: 190,
    imageUrl: Items.r1,
    isPopular: true,
    isSpicy: true,
    tags: ['Best Seller Roll', 'Tangy & Hot'],
  },
  {
    id: 'r2',
    name: 'Mighty Garlic Mayo Roll',
    urduName: 'مالا مال گارلک مایو رول',
    category: 'ROLL',
    description: 'Smoked chicken boti pieces soaked in deep rich mayonnaise blended with fresh crushed garlic cloves, snugly wrapped in soft paratha roll.',
    price: 210,
    imageUrl: Items.r2,
    isPopular: true,
    tags: ['Saucy Roll', 'Garlic Heavy'],
  },
  {
    id: 'r3',
    name: 'Crispy Zinger Puri Paratha Roll',
    urduName: 'زنگر پوری پراٹھا رول',
    category: 'ROLL',
    description: 'Golden fried breast chicken zinger strip sliced, sweet lettuce, hot burger mayo, rolled in a special crunchy fried puri paratha.',
    price: 250,
    imageUrl: Items.r3,
    isSpicy: true,
    tags: ['Crispy Twist', 'Puri Paratha Extra'],
  },

  // --- BEVERAGES ---
  {
    id: 'bv1',
    name: 'Carbonated Cold Drink Can (250ml)',
    urduName: 'کولڈ ڈرنک کین',
    category: 'BEVERAGES',
    description: 'Chilled carbonated soft drink. Choose from Pepsi, Sprite, Mirinda, or 7up.',
    price: 120,
    imageUrl: Items.bv1,
    tags: ['Chilled', 'Ice Cold'],
  },
  {
    id: 'bv2',
    name: 'Pakola Carbonated Green Cream Soda',
    urduName: 'پاکولا کریم سوڈا',
    category: 'BEVERAGES',
    description: 'Karachi\'s legendary traditional green cream soda served dead cold.',
    price: 150,
    imageUrl: Items.bv2,
    isPopular: true,
    tags: ['Karachi Nostalgia', 'Cold Green Sweet'],
  },
  {
    id: 'bv3',
    name: 'Nestle Mineral Water (500ml)',
    urduName: 'منرل واٹر',
    category: 'BEVERAGES',
    description: 'Pure, chilled and clean bottled drinking water.',
    price: 70,
    imageUrl: Items.bv3,
    tags: ['Hygiene Verified'],
  },

  // --- SIDES ---
  {
    id: 'sd1',
    name: 'Flaky Golden Puri Paratha',
    urduName: 'پوری پراٹھا اضافی',
    category: 'SIDES',
    description: 'Deep-fried hand-flaked paratha made with white flour. The ultimate partner for Charcoal barbecue Tikka.',
    price: 60,
    imageUrl: Items.sd1,
    isPopular: true,
    tags: ['Hot & Fresh', 'Fried'],
  },
  {
    id: 'sd2',
    name: 'Toasted Hamburger Bun',
    urduName: 'اضافی بند',
    category: 'SIDES',
    description: 'Fresh and soft sesame-seeded hamburger bun toasted with butter.',
    price: 40,
    imageUrl: Items.sd2,
    tags: ['Soft & Fresh'],
  },
  {
    id: 'sd3',
    name: 'Signature Creamy Garlic Mayo Sauce Dip',
    urduName: 'کامی اسپیشل گارلک سوس',
    category: 'SIDES',
    description: 'Our proprietary blended garlic, fresh cream, white pepper, and vinegar dip.',
    price: 40,
    imageUrl: Items.sd3,
    tags: ['Secret Recipe'],
  },
];
